export const SET_VUE_COMPONENTS_LIST = 'SET_VUE_COMPONENTS_LIST'
export const SET_DRAGGING = 'SET_DRAGGING';
export const SET_HIGHLIGHT_COMPONENT = 'SET_HIGHLIGHT_COMPONENT';
export const INSERT_COMPONENT = 'INSERT_COMPONENT';
export const REMOVE_COMPONENT = 'REMOVE_COMPONENT';
