export const SET_VUE_COMPONENTS_LIST = 'SET_VUE_COMPONENTS_LIST'
export const SET_DRAGGING = 'SET_DRAGGING';
export const SET_HIGHLIGHT_COMPONENT = 'SET_HIGHLIGHT_COMPONENT';
export const SET_SELECTED_COMPONENT = 'SET_SELECTED_COMPONENT';
export const SET_SHOW_PROPERTIES = 'SET_SHOW_PROPERTIES';
export const SET_PROP_VALUE = 'SET_PROP_VALUE';
export const INSERT_COMPONENT = 'INSERT_COMPONENT';
export const REMOVE_COMPONENT = 'REMOVE_COMPONENT';
